# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.cache/wt [current_project]
set_property parent.project_path /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_repo_paths /home/einsamer-wolf/Vivado/ip_location [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/anon_hw.bd
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_processing_system7_0_0/anon_hw_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_xbar_0/anon_hw_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_xbar_1/anon_hw_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_auto_pc_0/anon_hw_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_auto_us_0/anon_hw_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_auto_us_0/anon_hw_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_auto_us_1/anon_hw_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_auto_us_1/anon_hw_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/ip/anon_hw_auto_pc_1/anon_hw_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/anon_hw_ooc.xdc]
set_property is_locked true [get_files /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/anon_hw.bd]

read_verilog -library xil_defaultlib /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/proj.srcs/sources_1/bd/anon_hw/hdl/anon_hw_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top anon_hw_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef anon_hw_wrapper.dcp
catch { report_utilization -file anon_hw_wrapper_utilization_synth.rpt -pb anon_hw_wrapper_utilization_synth.pb }
