# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/anon_hw/anon_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw || ORIG_REF_NAME==anon_hw}]

# IP: bd/anon_hw/ip/anon_hw_processing_system7_0_0/anon_hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_processing_system7_0_0 || ORIG_REF_NAME==anon_hw_processing_system7_0_0}]

# IP: bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_axi_dma_0_0 || ORIG_REF_NAME==anon_hw_axi_dma_0_0}]

# IP: bd/anon_hw/ip/anon_hw_axi_mem_intercon_0/anon_hw_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_axi_mem_intercon_0 || ORIG_REF_NAME==anon_hw_axi_mem_intercon_0}]

# IP: bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==anon_hw_rst_processing_system7_0_50M_0}]

# IP: bd/anon_hw/ip/anon_hw_processing_system7_0_axi_periph_0/anon_hw_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==anon_hw_processing_system7_0_axi_periph_0}]

# IP: bd/anon_hw/ip/anon_hw_xbar_0/anon_hw_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_xbar_0 || ORIG_REF_NAME==anon_hw_xbar_0}]

# IP: bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_axi_gpio_0_0 || ORIG_REF_NAME==anon_hw_axi_gpio_0_0}]

# IP: bd/anon_hw/ip/anon_hw_xbar_1/anon_hw_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_xbar_1 || ORIG_REF_NAME==anon_hw_xbar_1}]

# IP: bd/anon_hw/ip/anon_hw_auto_pc_0/anon_hw_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_auto_pc_0 || ORIG_REF_NAME==anon_hw_auto_pc_0}]

# IP: bd/anon_hw/ip/anon_hw_auto_us_0/anon_hw_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_auto_us_0 || ORIG_REF_NAME==anon_hw_auto_us_0}]

# IP: bd/anon_hw/ip/anon_hw_auto_us_1/anon_hw_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_auto_us_1 || ORIG_REF_NAME==anon_hw_auto_us_1}]

# IP: bd/anon_hw/ip/anon_hw_auto_pc_1/anon_hw_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_auto_pc_1 || ORIG_REF_NAME==anon_hw_auto_pc_1}]

# XDC: bd/anon_hw/ip/anon_hw_processing_system7_0_0/anon_hw_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_processing_system7_0_0 || ORIG_REF_NAME==anon_hw_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_axi_dma_0_0 || ORIG_REF_NAME==anon_hw_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/anon_hw/ip/anon_hw_axi_dma_0_0/anon_hw_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_axi_dma_0_0 || ORIG_REF_NAME==anon_hw_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==anon_hw_rst_processing_system7_0_50M_0}]

# XDC: bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==anon_hw_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==anon_hw_rst_processing_system7_0_50M_0}]

# XDC: bd/anon_hw/ip/anon_hw_rst_processing_system7_0_50M_0/anon_hw_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_xbar_0/anon_hw_xbar_0_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_axi_gpio_0_0 || ORIG_REF_NAME==anon_hw_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_axi_gpio_0_0/anon_hw_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_axi_gpio_0_0 || ORIG_REF_NAME==anon_hw_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/anon_hw/ip/anon_hw_xbar_1/anon_hw_xbar_1_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_auto_pc_0/anon_hw_auto_pc_0_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_auto_us_0/anon_hw_auto_us_0_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_auto_us_0/anon_hw_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_auto_us_0 || ORIG_REF_NAME==anon_hw_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/anon_hw/ip/anon_hw_auto_us_1/anon_hw_auto_us_1_ooc.xdc

# XDC: bd/anon_hw/ip/anon_hw_auto_us_1/anon_hw_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==anon_hw_auto_us_1 || ORIG_REF_NAME==anon_hw_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/anon_hw/ip/anon_hw_auto_pc_1/anon_hw_auto_pc_1_ooc.xdc

# XDC: bd/anon_hw/anon_hw_ooc.xdc
