webtalk_init -webtalk_dir /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "土 9 24 17:06:37 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "p42b8opgee60op8eq2pa0k0pg5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.3_16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1474698267000" -context "sdk\\\\bsp/1474698267000"
webtalk_add_data -client sdk -key hwid -value "1465963221000" -context "sdk\\\\bsp/1474698267000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1474698267000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1474698267000"
webtalk_add_data -client sdk -key uid -value "1474698275000" -context "sdk\\\\application/1474698275000"
webtalk_add_data -client sdk -key hwid -value "1465963221000" -context "sdk\\\\application/1474698275000"
webtalk_add_data -client sdk -key bspid -value "1474698267000" -context "sdk\\\\application/1474698275000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1474698275000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1474698275000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1474698275000"
webtalk_transmit -clientid 3727098779 -regid "" -xml /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/einsamer-wolf/Vivado/proj/anon_pr_1/proj/sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
